sudo: required
dist: trusty
language: node_js
node_js: '8'
branches:
  only:
    - source


addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - openssl aes-256-cbc -K $encrypted_829172ed9bb8_key -iv $encrypted_829172ed9bb8_iv -in deploy.enc -out deployment/deploy -d
  - chmod 400 deployment/deploy # To prevent the thing from being a pain
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g @angular/cli karma angular-cli-ghpages

script: ng test --single-run && npm run deploy
